{
  lib,
  buildNpmPackage,
  fetchFromGitHub,
  fetchurl,
  makeBinaryWrapper,
  stdenvNoCC,
  ripgrep,
  fd,
  jq,
  writableTmpDirAsHomeHook,
  versionCheckHook,
  nix-update-script,
}:
buildNpmPackage (finalAttrs: {
  pname = "pi";
  version = "0.85.0";

  src = fetchFromGitHub {
    owner = "earendil-works";
    repo = "pi";
    rev = "v${finalAttrs.version}";
    hash = "sha256-gznGlneVCx3htxRiJq0/futm4qLR9Bzfv3UwP3ES9v0=";
  };

  npmDepsHash = "sha256-K/KiukwTHwu4HE8hUu7ur3bxggwfO0WL+QDI0FtxP3I=";

  # The provider model catalog (packages/ai/src/providers/data/) is generated by
  # a network fetch (models.dev plus provider APIs) and is gitignored upstream,
  # so it is absent from the source tarball. Restore it from the matching
  # published @earendil-works/pi-ai npm package, which ships the hydrated catalog
  # under dist/providers/data/. Bump this hash alongside version.
  modelData = fetchurl {
    url = "https://registry.npmjs.org/@earendil-works/pi-ai/-/pi-ai-${finalAttrs.version}.tgz";
    hash = "sha256-RhiL2stVWgdGagER85Y/IJMqFhmeTWz7jUSn/l/G40I=";
  };

  preConfigure = ''
    mkdir -p packages/ai/src/providers/data
    tar --extract --gzip --file=${finalAttrs.modelData} \
      --directory=packages/ai/src/providers/data \
      --strip-components=4 \
      package/dist/providers/data
  '';

  npmWorkspace = "packages/coding-agent";
  npmRebuildFlags = ["--ignore-scripts"];

  nativeBuildInputs = [
    makeBinaryWrapper
    jq
  ];

  buildPhase = ''
    runHook preBuild

    # Mirrors upstream: npm run build:offline (see package.json and scripts/build-binaries.sh --offline-model-data)
    if jq -e '.scripts["build:offline"]' package.json > /dev/null 2>&1; then
      npm run build:offline
    else
      npx tsgo -p packages/telemetry/tsconfig.build.json || true
      npx tsgo -p packages/tui/tsconfig.build.json
      npx tsgo -p packages/ai/tsconfig.build.json
      npx tsgo -p packages/agent/tsconfig.build.json
      if [ -f packages/protocol/tsconfig.build.json ]; then npx tsgo -p packages/protocol/tsconfig.build.json; fi
      if [ -f packages/client/tsconfig.build.json ]; then npx tsgo -p packages/client/tsconfig.build.json; fi
      if [ -f packages/server/tsconfig.build.json ]; then npx tsgo -p packages/server/tsconfig.build.json; fi
      if [ -f packages/session-backends/sqlite-node/tsconfig.build.json ]; then npx tsgo -p packages/session-backends/sqlite-node/tsconfig.build.json; fi
      npm run build --workspace=packages/coding-agent
    fi

    runHook postBuild
  '';

  postInstall =
    ''
      local nm="$out/lib/node_modules/pi-monorepo/node_modules"

      # Copy all @earendil-works workspaces into installed node_modules
      for pkgJson in packages/*/package.json packages/*/*/package.json packages/*/*/*/package.json; do
        [ -f "$pkgJson" ] || continue
        dir=$(dirname "$pkgJson")
        if [ "$dir" = "packages/coding-agent" ]; then continue; fi
        pkg=$(jq -r '.name // empty' "$pkgJson")
        case "$pkg" in
          @earendil-works/*)
            if [ -e "$nm/$pkg" ] || [ -L "$nm/$pkg" ]; then rm -rf "$nm/$pkg"; fi
            mkdir -p "$(dirname "$nm/$pkg")"
            cp -r "$dir" "$nm/$pkg"
            ;;
        esac
      done

      find "$nm" -type l -lname '*/packages/*' -delete 2>/dev/null || true
      find "$nm/.bin" -xtype l -delete 2>/dev/null || true
    ''
    + lib.optionalString stdenvNoCC.hostPlatform.isDarwin ''
      # Remove foreign Linux binaries that make audit-tmpdir try to inspect ELF
      # RPATHs with patchelf
      rm -rf \
        "$nm/@anthropic-ai/sandbox-runtime/dist/vendor/seccomp" \
        "$nm/@anthropic-ai/sandbox-runtime/vendor/seccomp"
    '';

  postFixup = "wrapProgram $out/bin/pi --prefix PATH : ${
    lib.makeBinPath [
      ripgrep
      fd
    ]
  } --set-default PI_SKIP_VERSION_CHECK 1 --set-default PI_TELEMETRY 0";

  doInstallCheck = true;
  nativeInstallCheckInputs = [
    writableTmpDirAsHomeHook
    versionCheckHook
  ];

  versionCheckKeepEnvironment = ["HOME"];
  versionCheckProgram = "${placeholder "out"}/bin/pi";
  versionCheckProgramArg = "--version";

  passthru.updateScript = nix-update-script {
    extraArgs = [
      "--flake"
      "--custom-dep"
      "modelData"
    ];
  };

  meta = {
    description = "Pi coding agent";
    license = lib.licenses.mit;
    platforms = lib.platforms.unix;
  };
})
