# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}: {
  "@opencode-ai/plugin@1.0.224" = fetchurl {
    url = "https://registry.npmjs.org/@opencode-ai/plugin/-/plugin-1.0.224.tgz";
    hash = "sha512-V2Su55FI6NGyabFHo853+8r9h66q//gsYWCIODbwRs47qi4VfbFylfddJxQDD+/M/H7w0++ojbQC9YCLNDXdKw==";
  };
  "@opencode-ai/sdk@1.0.224" = fetchurl {
    url = "https://registry.npmjs.org/@opencode-ai/sdk/-/sdk-1.0.224.tgz";
    hash = "sha512-gODyWLDTaz38qISxRdJKsEiFqvJNcFzu4/awoSICIl8j8gx6qDxLsYWVp/ToO4LKXTvHMn8yyZpM3ZEdGhDC+g==";
  };
  "@types/node-notifier@8.0.5" = fetchurl {
    url = "https://registry.npmjs.org/@types/node-notifier/-/node-notifier-8.0.5.tgz";
    hash = "sha512-LX7+8MtTsv6szumAp6WOy87nqMEdGhhry/Qfprjm1Ma6REjVzeF7SCyvPtp5RaF6IkXCS9V4ra8g5fwvf2ZAYg==";
  };
  "@types/node@22.19.3" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-22.19.3.tgz";
    hash = "sha512-1N9SBnWYOJTrNZCdh/yJE+t910Y128BoyY+zBLWhL3r0TYzlTmFdXrPwHL9DyFZmlEXNQQolTZh3KHV31QDhyA==";
  };
  "growly@1.3.0" = fetchurl {
    url = "https://registry.npmjs.org/growly/-/growly-1.3.0.tgz";
    hash = "sha512-+xGQY0YyAWCnqy7Cd++hc2JqMYzlm0dG30Jd0beaA64sROr8C4nt8Yc9V5Ro3avlSUDTN0ulqP/VBKi1/lLygw==";
  };
  "is-docker@2.2.1" = fetchurl {
    url = "https://registry.npmjs.org/is-docker/-/is-docker-2.2.1.tgz";
    hash = "sha512-F+i2BKsFrH66iaUFc0woD8sLy8getkwTwtOBjvs56Cx4CgJDeKQeqfz8wAYiSb8JOprWhHH5p77PbmYCvvUuXQ==";
  };
  "is-docker@3.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-docker/-/is-docker-3.0.0.tgz";
    hash = "sha512-eljcgEDlEns/7AXFosB5K/2nCM4P7FQPkGc/DWLy5rmFEWvZayGrik1d9/QIY5nJ4f9YsVvBkA6kJpHn9rISdQ==";
  };
  "is-inside-container@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/is-inside-container/-/is-inside-container-1.0.0.tgz";
    hash = "sha512-KIYLCCJghfHZxqjYBE7rEy0OBuTd5xCHS7tHVgvCLkx7StIoaxwNW3hCALgEUjFfeRk+MG/Qxmp/vtETEF3tRA==";
  };
  "is-wsl@2.2.0" = fetchurl {
    url = "https://registry.npmjs.org/is-wsl/-/is-wsl-2.2.0.tgz";
    hash = "sha512-fKzAra0rGJUUBwGBgNkHZuToZcn+TtXHpeCgmkMJMMYx1sQDYaCSyjJBSCa2nH1DGm7s3n1oBnohoVTBaN7Lww==";
  };
  "is-wsl@3.1.1" = fetchurl {
    url = "https://registry.npmjs.org/is-wsl/-/is-wsl-3.1.1.tgz";
    hash = "sha512-e6rvdUCiQCAuumZslxRJWR/Doq4VpPR82kqclvcS0efgt430SlGIk05vdCN58+VrzgtIcfNODjozVielycD4Sw==";
  };
  "isexe@2.0.0" = fetchurl {
    url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
    hash = "sha512-RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
  };
  "node-notifier@10.0.1" = fetchurl {
    url = "https://registry.npmjs.org/node-notifier/-/node-notifier-10.0.1.tgz";
    hash = "sha512-YX7TSyDukOZ0g+gmzjB6abKu+hTGvO8+8+gIFDsRCU2t8fLV/P2unmt+LGFaIa4y64aX98Qksa97rgz4vMNeLQ==";
  };
  "semver@7.7.3" = fetchurl {
    url = "https://registry.npmjs.org/semver/-/semver-7.7.3.tgz";
    hash = "sha512-SdsKMrI9TdgjdweUSR9MweHA4EJ8YxHn8DFaDisvhVlUOe4BF1tLD7GAj0lIqWVl+dPb/rExr0Btby5loQm20Q==";
  };
  "shellwords@0.1.1" = fetchurl {
    url = "https://registry.npmjs.org/shellwords/-/shellwords-0.1.1.tgz";
    hash = "sha512-vFwSUfQvqybiICwZY5+DAWIPLKsWO31Q91JSKl3UYv+K5c2QRPzn0qzec6QPu1Qc9eHYItiP3NdJqNVqetYAww==";
  };
  "typescript@5.9.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
    hash = "sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
  };
  "undici-types@6.21.0" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-6.21.0.tgz";
    hash = "sha512-iwDZqg0QAGrg9Rav5H4n0M64c3mkR59cJ6wQp+7C4nI0gsmExaedaYLNO44eT4AtBBwjbTiGPMlt2Md0T9H9JQ==";
  };
  "uuid@8.3.2" = fetchurl {
    url = "https://registry.npmjs.org/uuid/-/uuid-8.3.2.tgz";
    hash = "sha512-+NYs2QeMWy+GWFOEm9xnn6HCDp0l7QBD7ml8zLUmJ+93Q5NF0NocErnwkTkXVFNiX3/fpC6afS8Dhb/gz7R7eg==";
  };
  "which@2.0.2" = fetchurl {
    url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
    hash = "sha512-BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
  };
  "zod@4.1.8" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-4.1.8.tgz";
    hash = "sha512-5R1P+WwQqmmMIEACyzSvo4JXHY5WiAFHRMg+zBZKgKS+Q1viRa0C1hmUKtHltoIFKtIdki3pRxkmpP74jnNYHQ==";
  };
}
