{
  lib,
  stdenv,
  rustPlatform,
  callPackage,
  runCommand,
  fetchFromGitHub,
  zig_0_15,
  zstd,
  pkg-config,
  git,
  cctools,
  xcbuild,
  nix-update-script,
}: let
  # Pinned at the latest stable herdr tag. Bump via `passthru.updateScript`
  # (nix-update) which rewrites `version` + the `src` hash. The vendored Zig
  # dep hashes live inside the fetched herdr source
  # (vendor/libghostty-vt/build.zig.zon.nix, generated by zon2nix upstream), so
  # they update themselves when `src` advances — no extra hash to maintain,
  # unlike nixpkgs' `zig_0_15.fetchDeps` form.
  version = "0.8.2";

  src = fetchFromGitHub {
    owner = "ogulcancelik";
    repo = "herdr";
    tag = "v${version}";
    # Source hash matches nixpkgs by-name/he/herdr for v0.7.3 (proven FOD hash).
    hash = "sha256-sEGIN3dLZasaHob3EHscWBCIQHflMQVchYmzgsETDk4=";
  };

  # Reproduce herdr's own upstream packaging (nix/package.nix) for the vendored
  # libghostty-vt Zig deps. We callPackage the zon2nix-generated file that
  # ships inside the herdr source so we use the same tooling the remote repo
  # uses, rather than a re-implementation. The deps build sandbox-safe: every
  # artifact is a fixed-output fetch (fetchzip/fetchurl/fetchgit), and
  # `unpackZigArtifact` only runs `zig fetch` on an already-local store path.
  zigDeps = callPackage (import "${src}/vendor/libghostty-vt/build.zig.zon.nix") {
    name = "herdr-libghostty-vt-zig-cache";
    inherit zstd;
    # Herdr overrides the default linkFarm to produce a flat directory of
    # named dep entries (LIBGHOSTTY_VT_ZIG_SYSTEM_DIR layout). Reproduce it.
    linkFarm = name: entries:
      runCommand name {} ''
        mkdir -p $out
        ${lib.concatMapStringsSep "\n" (entry: ''
            cp -rL ${entry.path} $out/${entry.name}
          '')
          entries}
      '';
  };
in
  rustPlatform.buildRustPackage {
    pname = "herdr";
    inherit version src;

    # Cargo lock travels with the herdr source; pull it straight from there so
    # no separate cargoHash is needed. Add `outputHashes` here only if herdr
    # gains non-crates.io git deps in a future release.
    cargoLock = {
      lockFile = "${src}/Cargo.lock";
    };

    nativeBuildInputs =
      [
        git
        pkg-config
      ]
      ++ lib.optionals stdenv.hostPlatform.isDarwin [
        cctools
        xcbuild
      ];

    env = {
      LIBGHOSTTY_VT_OPTIMIZE = "ReleaseFast";
      LIBGHOSTTY_VT_SIMD = "true";
      LIBGHOSTTY_VT_ZIG_SYSTEM_DIR = zigDeps;
      ZIG = lib.getExe zig_0_15;
    };

    preBuild = ''
      export ZIG_GLOBAL_CACHE_DIR="$TMPDIR/zig-global-cache"
      export ZIG_LOCAL_CACHE_DIR="$TMPDIR/zig-local-cache"
    '';

    # Upstream Rust tests are covered by herdr's own CI; the Nix build is
    # intentionally build-only to avoid duplicating that suite (matches both
    # herdr's nix/package.nix and nixpkgs' by-name derivation).
    doCheck = false;

    passthru.updateScript = nix-update-script {
      extraArgs = ["--flake"];
    };

    meta = {
      description = "Agent multiplexer that lives in your terminal";
      homepage = "https://herdr.dev";
      changelog = "https://github.com/ogulcancelik/herdr/releases/tag/v${version}";
      license = lib.licenses.agpl3Plus;
      mainProgram = "herdr";
      platforms = lib.platforms.linux ++ lib.platforms.darwin;
    };
  }
