name: Build And Publish

on:
    push:
        branches: [main]

concurrency:
    group: build-publish-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                system: [x86_64-linux]
        steps:
            - uses: actions/checkout@v6

            - uses: cachix/install-nix-action@v31
              with:
                  extra_nix_config: |
                      access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

            - uses: cachix/cachix-action@v17
              with:
                  name: auxera
                  authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

            - name: Build package outputs
              run: |
                  system="${{ matrix.system }}"
                  expr="pkgs: builtins.concatStringsSep \"\\n\" (map (name: \".#packages.${system}.\" + name) (builtins.attrNames pkgs))"
                  nix eval --raw ".#packages.${system}" --apply "$expr" | xargs -r nix build --print-build-logs --system "$system"
