name: Commit changes and create a PR

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      title:
        required: true
        type: string
      body:
        required: false
        type: string
      changes:
        required: false
        type: boolean
        default: false
      auto-merge:
        required: false
        type: boolean
        default: true

jobs:
  commit-and-pr:
    runs-on: ubuntu-latest
    steps:
      - id: check-changes
        run: |
          if git diff --stat | grep -q .; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push
        if: inputs.changes || steps.check-changes.outputs.has_changes
        run: |
          git checkout -b ${{ inputs.branch }}
          git add .
          git commit -m "${{ inputs.title }}"
          git push -u origin ${{ inputs.branch }}

      - name: Create PR
        if: inputs.changes || steps.check-changes.outputs.has_changes
        env:
          GH_TOKEN: ${{ steps.bot-token.outputs.token }}
        run: |
          gh pr create \
            --base main \
            --head ${{ inputs.branch }} \
            --title "${{ inputs.title }}" \
            --body "${{ inputs.body }}" \
            --label "automated,dependencies"
            ${{ inputs.auto-merge == 'true' && '--auto-merge' || '' }}
